### ISSUE TITLE
After 1.1.0 upgrade, using 'auto' in spacing throws parse error

### ISSUE THREAD

**Issue by chasegiunta** [tailwindcss/tailwindcss#1070]
Weird error that's preventing upgrade from 1.1.0. 

Now when specifying `auto: 'auto',` in spacing key, like
```
theme: {
  spacing: {
    auto: 'auto'
  }
}
```
a parse error is thrown:
```
Module build failed (from ./node_modules/postcss-loader/src/index.js):
Error: Parse error on line 1:
auto * -1
^
Expecting 'SUB', 'LPAREN', 'NESTED_CALC', 'NUMBER', 'CSS_VAR', 'LENGTH', 'ANGLE', 'TIME', 'FREQ', 'RES', 'EMS', 'EXS', 'CHS', 'REMS', 'VHS', 'VWS', 'VMINS', 'VMAXS', 'PERCENTAGE', got 'PREFIX'
    at Parser.parseError (/Users/chasegiunta/Sites/heimbbq/node_modules/reduce-css-calc/dist/parser.js:160:21)
    at Parser.parse (/Users/chasegiunta/Sites/heimbbq/node_modules/reduce-css-calc/dist/parser.js:227:22)
    at /Users/chasegiunta/Sites/heimbbq/node_modules/reduce-css-calc/dist/index.js:39:30
    at walk (/Users/chasegiunta/Sites/heimbbq/node_modules/postcss-value-parser/lib/walk.js:19:7)
    at ValueParser.walk (/Users/chasegiunta/Sites/heimbbq/node_modules/postcss-value-parser/lib/index.js:18:3)
    at exports.default (/Users/chasegiunta/Sites/heimbbq/node_modules/reduce-css-calc/dist/index.js:29:51)
    at Object.keys.filter.reduce (/Users/chasegiunta/Sites/heimbbq/node_modules/tailwindcss/lib/util/resolveConfig.js:25:47)
    at Array.reduce (<anonymous>)
    at negative (/Users/chasegiunta/Sites/heimbbq/node_modules/tailwindcss/lib/util/resolveConfig.js:24:65)
    at Object.margin (/Users/chasegiunta/Sites/heimbbq/tailwind.config.js:309:10)
    at Object.keys.reduce (/Users/chasegiunta/Sites/heimbbq/node_modules/tailwindcss/lib/util/resolveConfig.js:68:65)
    at Array.reduce (<anonymous>)
    at resolveFunctionKeys (/Users/chasegiunta/Sites/heimbbq/node_modules/tailwindcss/lib/util/resolveConfig.js:66:30)
    at resolveConfig (/Users/chasegiunta/Sites/heimbbq/node_modules/tailwindcss/lib/util/resolveConfig.js:75:12)
    at /Users/chasegiunta/Sites/heimbbq/node_modules/tailwindcss/lib/index.js:67:37
    at /Users/chasegiunta/Sites/heimbbq/node_modules/tailwindcss/lib/processTailwindFeatures.js:32:20

 @ ./node_modules/vue-style-loader??ref--7-oneOf-1-0!./node_modules/css-loader??ref--7-oneOf-1-1!./node_modules/vue-loader/lib/loaders/stylePostLoader.js!./node_modules/postcss-loader/src??ref--7-oneOf-1-2!./node_modules/cache-loader/dist/cjs.js??ref--0-0!./node_modules/vue-loader/lib??vue-loader-options!./src/components/Embed.vue?vue&type=style&index=0&lang=postcss& 4:14-375 14:3-18:5 15:22-383
 @ ./src/components/Embed.vue?vue&type=style&index=0&lang=postcss&
 @ ./src/components/Embed.vue
 @ ./src/components sync [A-Z]\w+\.(vue|js)$
 @ ./src/components.js
 @ ./src/main.js
 @ multi (webpack)-dev-server/client?http://localhost:8080/sockjs-node (webpack)/hot/dev-server.js ./src/main.js
```

**Comment by adamwathan** [comment]
Working on a fix – sorry!

**Comment by chasegiunta** [comment]
Lol don't apologize man - this is free OSS! No rush from me! Thanks for taking a look.

**Comment by adamwathan** [comment]
Fixed and tag!
