### ISSUE TITLE
Unable to use PurgeCSS due to CssSyntaxError

### ISSUE THREAD

**Issue by alphametric** [tailwindcss/tailwindcss#1084]
After recently upgrading to Tailwind CSS v1.1, I encounter the following problem when running a production build through Laravel Mix:

```
CssSyntaxError: <css input>:162114:23: Unknown word
    at Input.error (/Users/**REDACTED**/Documents/Code/Apps/**REDACTED**/node_modules/postcss/lib/input.js:130:16)
    at Parser.unknownWord (/Users/**REDACTED**/Documents/Code/Apps/**REDACTED**/node_modules/postcss/lib/parser.js:563:22)
    at Parser.other (/Users/**REDACTED**/Documents/Code/Apps/**REDACTED**/node_modules/postcss/lib/parser.js:168:12)
    at Parser.parse (/Users/**REDACTED**/Documents/Code/Apps/**REDACTED**/node_modules/postcss/lib/parser.js:77:16)
    at Function.parse (/Users/**REDACTED**/Documents/Code/Apps/**REDACTED**/node_modules/postcss/lib/parse.js:17:12)
    at Purgecss.getCssContents (/Users/**REDACTED**/Documents/Code/Apps/**REDACTED**/node_modules/purgecss/lib/purgecss.js:478:31)
    at Purgecss.purge (/Users/**REDACTED**/Documents/Code/Apps/**REDACTED**/node_modules/purgecss/lib/purgecss.js:443:19)
    at /Users/**REDACTED**/Documents/Code/Apps/**REDACTED**/node_modules/purgecss-webpack-plugin/lib/purgecss-webpack-plugin.js:282:33
    at Array.forEach (<anonymous>)
    at /Users/**REDACTED**/Documents/Code/Apps/**REDACTED**/node_modules/purgecss-webpack-plugin/lib/purgecss-webpack-plugin.js:247:23
    at Array.forEach (<anonymous>)
    at PurgecssPlugin.runPluginHook (/Users/**REDACTED**/Documents/Code/Apps/**REDACTED**/node_modules/purgecss-webpack-plugin/lib/purgecss-webpack-plugin.js:235:26)
    at /Users/**REDACTED**/Documents/Code/Apps/**REDACTED**/node_modules/purgecss-webpack-plugin/lib/purgecss-webpack-plugin.js:219:18
    at _next0 (eval at create (/Users/**REDACTED**/Documents/Code/Apps/**REDACTED**/node_modules/tapable/lib/HookCodeFactory.js:33:10), <anonymous>:10:1)
    at eval (eval at create (/Users/**REDACTED**/Documents/Code/Apps/**REDACTED**/node_modules/tapable/lib/HookCodeFactory.js:33:10), <anonymous>:24:1)
    at /Users/**REDACTED**/Documents/Code/Apps/**REDACTED**/node_modules/extract-text-webpack-plugin/dist/index.js:330:9
    at AsyncSeriesHook.eval [as callAsync] (eval at create (/Users/**REDACTED**/Documents/Code/Apps/**REDACTED**/node_modules/tapable/lib/HookCodeFactory.js:33:10), <anonymous>:20:1)
    at AsyncSeriesHook.lazyCompileHook (/Users/**REDACTED**/Documents/Code/Apps/**REDACTED**/node_modules/tapable/lib/Hook.js:154:20)
    at /Users/**REDACTED**/Documents/Code/Apps/**REDACTED**/node_modules/webpack/lib/Compilation.js:1367:32
    at eval (eval at create (/Users/**REDACTED**/Documents/Code/Apps/**REDACTED**/node_modules/tapable/lib/HookCodeFactory.js:33:10), <anonymous>:11:1)
    at /Users/**REDACTED**/Documents/Code/Apps/**REDACTED**/node_modules/extract-text-webpack-plugin/dist/index.js:296:11
    at /Users/**REDACTED**/Documents/Code/Apps/**REDACTED**/node_modules/async/dist/async.js:473:16
    at iteratorCallback (/Users/**REDACTED**/Documents/Code/Apps/**REDACTED**/node_modules/async/dist/async.js:1064:13)
    at /Users/**REDACTED**/Documents/Code/Apps/**REDACTED**/node_modules/async/dist/async.js:969:16
    at /Users/**REDACTED**/Documents/Code/Apps/**REDACTED**/node_modules/extract-text-webpack-plugin/dist/index.js:274:13
    at /Users/**REDACTED**/Documents/Code/Apps/**REDACTED**/node_modules/async/dist/async.js:473:16
    at iteratorCallback (/Users/**REDACTED**/Documents/Code/Apps/**REDACTED**/node_modules/async/dist/async.js:1064:13)
    at /Users/**REDACTED**/Documents/Code/Apps/**REDACTED**/node_modules/async/dist/async.js:969:16
    at /Users/**REDACTED**/Documents/Code/Apps/**REDACTED**/node_modules/extract-text-webpack-plugin/dist/index.js:261:26
    at callback (/Users/**REDACTED**/Documents/Code/Apps/**REDACTED**/node_modules/webpack/lib/Compilation.js:1186:5)
    at /Users/**REDACTED**/Documents/Code/Apps/**REDACTED**/node_modules/webpack/lib/Compilation.js:1209:5
    at processTicksAndRejections (internal/process/task_queues.js:75:11)
```

Just to confirm, the issue only occurs on production builds (where PurgeCSS is being applied).

Not sure if this is Tailwind related or not, but the same configuration worked with Tailwind V1.0

Thanks!

**Comment by adamwathan** [comment]
Can you create a project that reproduces the issue and publish it to GitHub?

**Comment by alphametric** [comment]
Running NPM update today seems to have fixed the problem.

**Comment by AlextheYounga** [comment]
I had this same issue trying to deploy to heroku. I spent two days looking around trying to find what's causing it. I was able to solve it using purge CSS. Here is the stack trace for reference:

```
remote:        CssSyntaxError: /tmp/build_0a357afb/css/application-b983b4e6.css:5393:69: Unknown word
remote:            at Input.error (/tmp/build_0a357afb/node_modules/postcss/lib/input.js:128:16)
remote:            at Parser.unknownWord (/tmp/build_0a357afb/node_modules/postcss/lib/parser.js:561:22)
remote:            at Parser.other (/tmp/build_0a357afb/node_modules/postcss/lib/parser.js:166:12)
remote:            at Parser.parse (/tmp/build_0a357afb/node_modules/postcss/lib/parser.js:75:16)
remote:            at parse (/tmp/build_0a357afb/node_modules/postcss/lib/parse.js:17:12)
remote:            at new LazyResult (/tmp/build_0a357afb/node_modules/postcss/lib/lazy-result.js:64:16)
remote:            at Processor.<anonymous> (/tmp/build_0a357afb/node_modules/postcss/lib/processor.js:142:12)
remote:            at Processor.process (/tmp/build_0a357afb/node_modules/postcss/lib/processor.js:121:23)
remote:            at Function.creator.process (/tmp/build_0a357afb/node_modules/postcss/lib/postcss.js:148:43)
remote:            at OptimizeCssAssetsWebpackPlugin.processCss (/tmp/build_0a357afb/node_modules/optimize-css-assets-webpack-plugin/src/index.js:73:21)
remote:            at Object.processor (/tmp/build_0a357afb/node_modules/optimize-css-assets-webpack-plugin/src/index.js:13:18)
remote:            at /tmp/build_0a357afb/node_modules/last-call-webpack-plugin/src/index.js:150:10
remote:            at arrayEach (/tmp/build_0a357afb/node_modules/lodash/_arrayEach.js:15:9)
remote:            at forEach (/tmp/build_0a357afb/node_modules/lodash/forEach.js:38:10)
remote:            at OptimizeCssAssetsWebpackPlugin.process (/tmp/build_0a357afb/node_modules/last-call-webpack-plugin/src/index.js:147:5)
remote:            at /tmp/build_0a357afb/node_modules/last-call-webpack-plugin/src/index.js:178:28
remote:            at AsyncSeriesHook.eval [as callAsync] (eval at create (/tmp/build_0a357afb/node_modules/tapable/lib/HookCodeFactory.js:33:10), <anonymous>:20:17)
remote:            at AsyncSeriesHook.lazyCompileHook (/tmp/build_0a357afb/node_modules/tapable/lib/Hook.js:154:20)
remote:            at /tmp/build_0a357afb/node_modules/webpack/lib/Compilation.js:1409:36
remote:            at AsyncSeriesHook.eval [as callAsync] (eval at create (/tmp/build_0a357afb/node_modules/tapable/lib/HookCodeFactory.js:33:10), <anonymous>:4:1)
remote:            at AsyncSeriesHook.lazyCompileHook (/tmp/build_0a357afb/node_modules/tapable/lib/Hook.js:154:20)
remote:            at /tmp/build_0a357afb/node_modules/webpack/lib/Compilation.js:1405:32
remote:            at AsyncSeriesHook.eval [as callAsync] (eval at create (/tmp/build_0a357afb/node_modules/tapable/lib/HookCodeFactory.js:33:10), <anonymous>:4:1)
remote:            at AsyncSeriesHook.lazyCompileHook (/tmp/build_0a357afb/node_modules/tapable/lib/Hook.js:154:20)
remote:            at Compilation.seal (/tmp/build_0a357afb/node_modules/webpack/lib/Compilation.js:1342:27)
remote:            at /tmp/build_0a357afb/node_modules/webpack/lib/Compiler.js:675:18
remote:            at /tmp/build_0a357afb/node_modules/webpack/lib/Compilation.js:1261:4
remote:            at AsyncSeriesHook.eval [as callAsync] (eval at create (/tmp/build_0a357afb/node_modules/tapable/lib/HookCodeFactory.js:33:10), <anonymous>:22:1)
remote:            at AsyncSeriesHook.lazyCompileHook (/tmp/build_0a357afb/node_modules/tapable/lib/Hook.js:154:20)
remote:            at Compilation.finish (/tmp/build_0a357afb/node_modules/webpack/lib/Compilation.js:1253:28)
remote:            at /tmp/build_0a357afb/node_modules/webpack/lib/Compiler.js:672:17
remote:            at eval (eval at create (/tmp/build_0a357afb/node_modules/tapable/lib/HookCodeFactory.js:33:10), <anonymous>:9:1)
remote:            at /tmp/build_0a357afb/node_modules/webpack/lib/Compilation.js:1185:12
remote:            at /tmp/build_0a357afb/node_modules/webpack/lib/Compilation.js:1097:9
remote:            at processTicksAndRejections (internal/process/task_queues.js:79:11)
remote:
remote:
remote:  !
remote:  !     Precompiling assets failed.
```

I was running these packages and versions for reference:
```
  "dependencies": {
    "@rails/webpacker": "5.2.1",
    "@tailwindcss/postcss7-compat": "npm:@tailwindcss/postcss7-compat@^2.0.2",
    "autoprefixer": "^9.8.6",
    "jquery": "^3.5.1",
    "postcss": "^7.0.35",
    "postcss-scss": "^3.0.4",
    "tailwindcss": "npm:@tailwindcss/postcss7-compat@^2.0.2"
  }
```

I was able to solve it by adding purge CSS to the tailwind.config.js:

```
module.exports = {
  purge: [
    'app/views/**/*.html.erb',
    'app/assets/stylesheets/**/*.scss',
    'app/assets/javascripts/**/*.js',
  ],
```

I have no idea why this did the trick, but I tested it a couple of times and I'm 100% positive. Failure to include purgeCSS settings in tailwind.config.js led to this issue.
