### ISSUE TITLE
Whitelist corePlugins for negativeMargin

### ISSUE THREAD

**Issue by JanaVanMaele** [tailwindcss/tailwindcss#1246]
In the manual for the customization of the configuration you describe you can whitelist the corePlugins. In the list of possible whitelist corePlugins you mention 'negativeMargin'. 
If I add `negativeMargin` to the array

<img width="700" alt="corePluginsList" src="https://user-images.githubusercontent.com/3185604/69967790-6caf1280-1519-11ea-82ea-71981b016429.png">

```
module.exports = {
  corePlugins: [
    'negativeMargin'
  ]
}
```

I get following error in my console

```
TypeError: plugins[pluginName] is not a function
        at /Users/janavanmaele/Sites/Yesplan-app/node_modules/tailwindcss/lib/util/configurePlugins.js:12:59
        at Array.map (<anonymous>)
        at _default (/Users/janavanmaele/Sites/Yesplan-app/node_modules/tailwindcss/lib/util/configurePlugins.js:12:22)
        at _default (/Users/janavanmaele/Sites/Yesplan-app/node_modules/tailwindcss/lib/corePlugins.js:151:40)
        at /Users/janavanmaele/Sites/Yesplan-app/node_modules/tailwindcss/lib/processTailwindFeatures.js:33:88
        at LazyResult.run (/Users/janavanmaele/Sites/Yesplan-app/node_modules/postcss-loader/node_modules/postcss/lib/lazy-result.js:295:14)
        at LazyResult.asyncTick (/Users/janavanmaele/Sites/Yesplan-app/node_modules/postcss-loader/node_modules/postcss/lib/lazy-result.js:208:26)
        at LazyResult.asyncTick (/Users/janavanmaele/Sites/Yesplan-app/node_modules/postcss-loader/node_modules/postcss/lib/lazy-result.js:221:14)
        at /Users/janavanmaele/Sites/Yesplan-app/node_modules/postcss-loader/node_modules/postcss/lib/lazy-result.js:213:17
```

I do not have the issue with one of the other coreplugins.

**Comment by adamwathan** [comment]
Ah that's a mistake in the docs, there used to be a negativeMargin plugin in v0.x but it was combined with the regular margin plugin for 1.0.
