### ISSUE TITLE
Webpack plugin arguments[i].apply is not a function

### ISSUE THREAD

**Issue by ruigomeseu** [tailwindcss/tailwindcss#185]
I want to try out tailwind in a sideproject I'm building.

It's a Vue.js app using Webpack to transpile everything.

I followed the installation section instructions but I'm stuck with this error while running webpack:

```
/Users/ruigomes/Projects/Javascript/feedbeaver-frontend/node_modules/webpack/bin/webpack.js:345
			throw e;
			^

TypeError: arguments[i].apply is not a function
    at Compiler.apply (/Users/ruigomes/Projects/Javascript/feedbeaver-frontend/node_modules/tapable/lib/Tapable.js:375:16)
    at webpack (/Users/ruigomes/Projects/Javascript/feedbeaver-frontend/node_modules/webpack/lib/webpack.js:33:19)
    at processOptions (/Users/ruigomes/Projects/Javascript/feedbeaver-frontend/node_modules/webpack/bin/webpack.js:335:15)
    at yargs.parse (/Users/ruigomes/Projects/Javascript/feedbeaver-frontend/node_modules/webpack/bin/webpack.js:393:2)
    at Object.Yargs.self.parse (/Users/ruigomes/Projects/Javascript/feedbeaver-frontend/node_modules/webpack/node_modules/yargs/yargs.js:533:18)
    at Object.<anonymous> (/Users/ruigomes/Projects/Javascript/feedbeaver-frontend/node_modules/webpack/bin/webpack.js:152:7)
    at Module._compile (module.js:624:30)
    at Object.Module._extensions..js (module.js:635:10)
    at Module.load (module.js:545:32)
    at tryModuleLoad (module.js:508:12)
    at Function.Module._load (module.js:500:3)
    at Function.Module.runMain (module.js:665:10)
    at startup (bootstrap_node.js:187:16)
    at bootstrap_node.js:608:3
error Command failed with exit code 1.
```

My webpack.config.js file is: https://pastebin.com/recnnbDH

I might be missing something obvious but I can't for the life of me figure it out.

Thanks in advance!

**Comment by ruigomeseu** [comment]
I managed to get it running using the `postcss.config.js` file instead, as in the tailwindcss/webpack-starter repo. Maybe that could be in the docs?

**Comment by adamwathan** [comment]
Hey @ruigomeseu glad you got it sorted out! The docs do talk about that file, is there anything you think we should change?

![image](https://user-images.githubusercontent.com/4323180/32684601-2e97bef0-c653-11e7-9c8e-dff89a147bd4.png)

**Comment by ruigomeseu** [comment]
Oh, I completely missed that, I just assumed it should go into the webpack config. My bad, it's super clear in the docs!

Thanks @adamwathan, I'm closing the issue.

Just as a side note, I pretty much hate doing any CSS work and with Tailwind I'm quite enjoying a redesign I'm doing in a sideproject, so kudos to you and the rest of the team!

**Comment by kopahead** [comment]
Also just made the same mistake. Love the docs but that one part might be a little deceiving. Eventually solved it by studying the example here: https://github.com/tailwindcss/webpack-starter

**Comment by ernsheong** [comment]
Putting `// in postcss.config.js` at the top of the code snippet would help a lot. I also overlooked that sentence. It looks very very much like a webpack config file...
