### ISSUE TITLE
TypeError: i.filter is not a function when using purge: true and content: [...]

### ISSUE THREAD

**Issue by Sevensidedmarble** [tailwindcss/tailwindcss#1982]
When using the alternative syntax in `tailwind.config.js` where purge is an object instead of an array, purge is set to true, and the files are listed under content, everything breaks.

Example:
```
// tailwind.config.js
module.exports = {
  purge: {
    enabled: true,
    content: './src/pages/**/*.cr',
  },
  theme: {},
  variants: {},
  plugins: [],
}
```

It looks breaks whenever you run with an error that looks like this:

```
[!] (plugin postcss) TypeError: i.filter is not a function
src/css/app.css
TypeError: i.filter is not a function
    at /.../node_modules/tailwindcss/node_modules/@fullhuman/postcss-purgecss/lib/postcss-purgecss.js:1:421
    at LazyResult.run (/.../node_modules/postcss/lib/lazy-result.js:295:14)
    at LazyResult.asyncTick (/.../node_modules/postcss/lib/lazy-result.js:208:26)
    at LazyResult.asyncTick (/.../node_modules/postcss/lib/lazy-result.js:221:14)
    at LazyResult.asyncTick (/.../node_modules/postcss/lib/lazy-result.js:221:14)
    at LazyResult.asyncTick (/.../node_modules/postcss/lib/lazy-result.js:221:14)
    at LazyResult.asyncTick (/.../node_modules/postcss/lib/lazy-result.js:221:14)
    at LazyResult.asyncTick (/.../node_modules/postcss/lib/lazy-result.js:221:14)
    at LazyResult.asyncTick (/.../node_modules/postcss/lib/lazy-result.js:221:14)
    at LazyResult.asyncTick (/.../node_modules/postcss/lib/lazy-result.js:221:14)
```

I'm using rollup as my bundler, but I don't think that makes a difference. I'm confident this is a tailwind error, not a purgecss error, although the stacktrace does come from purgecss, because it only happens with the config posted above.

**Comment by adamwathan** [comment]
Content should be an array of paths, not a string 👍🏻
GitHub <notifications@github.com> wrote:
“When using the alternative syntax in tailwind.config.js where purge is an object instead of an array, purge is set to true, and the files are listed under content, everything breaks.

Example:

// tailwind.config.js
module.exports = {
  purge: {
    enabled: true,
    content: './src/pages/**/*.cr',
  },
  theme: {},
  variants: {},
  plugins: [],
}

It looks breaks whenever you run with an error that looks like this:

[!] (plugin postcss) TypeError: i.filter is not a function
src/css/app.css
TypeError: i.filter is not a function
    at /.../node_modules/tailwindcss/node_modules/@fullhuman/postcss-purgecss/lib/postcss-purgecss.js:1:421
    at LazyResult.run (/.../node_modules/postcss/lib/lazy-result.js:295:14)
    at LazyResult.asyncTick (/.../node_modules/postcss/lib/lazy-result.js:208:26)
    at LazyResult.asyncTick (/.../node_modules/postcss/lib/lazy-result.js:221:14)
    at LazyResult.asyncTick (/.../node_modules/postcss/lib/lazy-result.js:221:14)
    at LazyResult.asyncTick (/.../node_modules/postcss/lib/lazy-result.js:221:14)
    at LazyResult.asyncTick (/.../node_modules/postcss/lib/lazy-result.js:221:14)
    at LazyResult.asyncTick (/.../node_modules/postcss/lib/lazy-result.js:221:14)
    at LazyResult.asyncTick (/.../node_modules/postcss/lib/lazy-result.js:221:14)
    at LazyResult.asyncTick (/.../node_modules/postcss/lib/lazy-result.js:221:14)

I'm using rollup as my bundler, but I don't think that makes a difference. I'm confident this is a tailwind error, not a purgecss error, although the stacktrace does come from purgecss, because it only happens with the config posted above.”

**Comment by Sevensidedmarble** [comment]
Could we add an error message for the script reading the config to check that that is an array then? Cause that's an easy mistake to make and an easy thing to protect against with a good error message.

**Comment by adamwathan** [comment]
Yep we could likely do something like that although it's a bit of a slippery slope to introduce type-checking for every option. Going to close this issue but would accept a PR that added a more friendly error message for this mistake.
