### ISSUE TITLE
Unable to run the Tailwind init command...

### ISSUE THREAD

**Issue by PatrickWhitehouse** [tailwindcss/tailwindcss#372]
Getting this error. No idea what it means. 

/Users/Patrick/Desktop/portfolio-2018/node_modules/tailwindcss/lib/cli.js:58
_commander2.default.command('init [filename]').usage('[options] [filename]').action((filename = 'tailwind.js') => {
                                                                                              ^

SyntaxError: Unexpected token =
    at exports.runInThisContext (vm.js:53:16)
    at Module._compile (module.js:373:25)
    at Object.Module._extensions..js (module.js:416:10)
    at Module.load (module.js:343:32)
    at Function.Module._load (module.js:300:12)
    at Function.Module.runMain (module.js:441:10)
    at startup (node.js:139:18)
    at node.js:968:3

**Comment by adamwathan** [comment]
> Need to update to a newer version of Node; we transpile for Node 6.0 and up.

https://github.com/tailwindcss/discuss/issues/113#issuecomment-361715556

**Comment by evanvosberg** [comment]
@adamwathan I run in such an error even with Node 6.9.x and 8.1.x ...

Right on `require('tailwindcss')` I get an `SyntaxError: Unexpected token ...`.

**Comment by adamwathan** [comment]
Can you post the full stack trace?

**Comment by evanvosberg** [comment]
Thanks for quick response.

Do not get the full stack, that's why it's so hard to debug, but let me give you some more context.

Tailwind is running as part of a grunt task in a Jenkins job.

```
var tailwindcss = require('tailwindcss');

module.exports = {
    options: {
        map: false, // inline sourcemaps
        processors: [
            tailwindcss('tailwind.js'),
            require('autoprefixer')
        ]
    },
    dist: {
        files: [{
            expand: true,
            cwd: 'app/public/css',
            src: 'main.css',
            dest: 'app/public/css'
        }]
    }
};
```

Skip loading the config by removing line 7 does not help, only removing line 1 and 7 makes the grunt task running. Burt then it's without tailwind.

All this is running on Jenkins, its env has Node 6.9.1 or 8.9.1 and in both cases I get the error.

```
Loading "Gruntfile.js" tasks...ERROR
>> SyntaxError: Unexpected token ...
```

**Comment by evanvosberg** [comment]
Ok switche grunt into debug mode

```
>> SyntaxError: Unexpected token ...
>>   at exports.runInThisContext (vm.js:53:16)
>>   at Module._compile (module.js:374:25)
>>   at Object.Module._extensions..js (module.js:417:10)
>>   at Module.load (/data/jenkins/workspace/project-deploy/node_modules/coffeescript/lib/coffee-script/register.js:45:36)
>>   at Function.Module._load (module.js:301:12)
>>   at Module.require (module.js:354:17)
>>   at require (internal/module.js:12:17)
>>   at Object.<anonymous> (/data/jenkins/workspace/project-deploy/grunt/config/postcss.js:1:81)
>>   at Module._compile (module.js:410:26)
>>   at Object.Module._extensions..js (module.js:417:10)
>>   at Module.load (/data/jenkins/workspace/project-deploy/node_modules/coffeescript/lib/coffee-script/register.js:45:36)
>>   at Function.Module._load (module.js:301:12)
>>   at Module.require (module.js:354:17)
>>   at require (internal/module.js:12:17)
>>   at module.exports (/data/jenkins/workspace/project-deploy/node_modules/load-grunt-config/lib/readfile.js:22:16)
>>   at /data/jenkins/workspace/project-deploy/node_modules/load-grunt-config/lib/readconfigdir.js:23:18
>>   at Array.forEach (native)
>>   at module.exports (/data/jenkins/workspace/project-deploy/node_modules/load-grunt-config/lib/readconfigdir.js:22:13)
>>   at module.exports (/data/jenkins/workspace/project-deploy/node_modules/load-grunt-config/lib/gruntconfig.js:6:16)
>>   at module.exports (/data/jenkins/workspace/project-deploy/node_modules/load-grunt-config/index.js:31:16)
>>   at Object.module.exports (/data/jenkins/workspace/project-deploy/Gruntfile.js:12:33)
>>   at loadTask (/data/jenkins/workspace/project-deploy/node_modules/grunt/lib/grunt/task.js:315:10)
>>   at Task.task.init (/data/jenkins/workspace/project-deploy/node_modules/grunt/lib/grunt/task.js:434:5)
>>   at Object.grunt.tasks (/data/jenkins/workspace/project-deploy/node_modules/grunt/lib/grunt.js:111:8)
>>   at Object.module.exports [as cli] (/data/jenkins/workspace/project-deploy/node_modules/grunt/lib/grunt/cli.js:27:9)
>>   at Object.<anonymous> (/usr/local/lib/node_modules/grunt-cli/bin/grunt:44:20)
>>   at Module._compile (module.js:410:26)
>>   at Object.Module._extensions..js (module.js:417:10)
>>   at Module.load (module.js:344:32)
>>   at Function.Module._load (module.js:301:12)
>>   at Function.Module.runMain (module.js:442:10)
>>   at startup (node.js:136:18)
>>   at node.js:966:3
```

**Comment by evanvosberg** [comment]
Seems like the Jenkins NodeJS Plugin does not work correct ... so the process is running in a 4.x env.
