### ISSUE TITLE
1.0 Beta - Not compatible with Node v6.9.2

### ISSUE THREAD

**Issue by wking-io** [tailwindcss/tailwindcss#839]
Hey! 

I am using the 1.0 beta of Tailwind for our companies site and I am getting this error even though I read Tailwind supports Nodee v6.0.0 and up. Anything I can do to fix this? I am using PostCSS and Wepack. Here is the error.

```
> skillcrush-build-system@1.0.0 build /Users/wking/sites/learn_skillcrush/app/public
> webpack --mode=production --config=config/webpack.config.js

/Users/wking/sites/learn_skillcrush/app/public/node_modules/tailwindcss/lib/lib/substituteVariantsAtRules.js:57
    const variantGenerators = { ...defaultVariantGenerators,
                                ^^^
SyntaxError: Unexpected token ...
    at NativeCompileCache._moduleCompile (/Users/wking/sites/learn_skillcrush/app/public/node_modules/v8-compile-cache/v8-compile-cache.js:226:18)
    at Module._compile (/Users/wking/sites/learn_skillcrush/app/public/node_modules/v8-compile-cache/v8-compile-cache.js:172:36)
    at Object.Module._extensions..js (module.js:579:10)
    at Module.load (module.js:487:32)
    at tryModuleLoad (module.js:446:12)
    at Function.Module._load (module.js:438:3)
    at Module.require (module.js:497:17)
    at require (/Users/wking/sites/learn_skillcrush/app/public/node_modules/v8-compile-cache/v8-compile-cache.js:159:20)
    at Object.<anonymous> (/Users/wking/sites/learn_skillcrush/app/public/node_modules/tailwindcss/lib/processTailwindFeatures.js:16:57)
    at Module._compile (/Users/wking/sites/learn_skillcrush/app/public/node_modules/v8-compile-cache/v8-compile-cache.js:178:30)
    at Object.Module._extensions..js (module.js:579:10)
    at Module.load (module.js:487:32)
    at tryModuleLoad (module.js:446:12)
    at Function.Module._load (module.js:438:3)
    at Module.require (module.js:497:17)
    at require (/Users/wking/sites/learn_skillcrush/app/public/node_modules/v8-compile-cache/v8-compile-cache.js:159:20)
    at Object.<anonymous> (/Users/wking/sites/learn_skillcrush/app/public/node_modules/tailwindcss/lib/index.js:15:55)
    at Module._compile (/Users/wking/sites/learn_skillcrush/app/public/node_modules/v8-compile-cache/v8-compile-cache.js:178:30)
    at Object.Module._extensions..js (module.js:579:10)
    at Module.load (module.js:487:32)
    at tryModuleLoad (module.js:446:12)
    at Function.Module._load (module.js:438:3)
    at Module.require (module.js:497:17)
    at require (/Users/wking/sites/learn_skillcrush/app/public/node_modules/v8-compile-cache/v8-compile-cache.js:159:20)
    at postcssOptions (/Users/wking/sites/learn_skillcrush/app/public/config/webpack.config.js:14:5)
    at module.exports (/Users/wking/sites/learn_skillcrush/app/public/config/webpack.config.js:119:28)
    at handleFunction (/Users/wking/sites/learn_skillcrush/app/public/node_modules/webpack-cli/bin/prepareOptions.js:21:13)
    at prepareOptions (/Users/wking/sites/learn_skillcrush/app/public/node_modules/webpack-cli/bin/prepareOptions.js:9:5)
    at requireConfig (/Users/wking/sites/learn_skillcrush/app/public/node_modules/webpack-cli/bin/convert-argv.js:118:14)
    at /Users/wking/sites/learn_skillcrush/app/public/node_modules/webpack-cli/bin/convert-argv.js:124:17

npm ERR! Darwin 18.2.0
npm ERR! argv "/Users/wking/.nvm/versions/node/v6.9.2/bin/node" "/Users/wking/.nvm/versions/node/v6.9.2/bin/npm" "run" "build"
npm ERR! node v6.9.2
npm ERR! npm  v3.10.9
npm ERR! code ELIFECYCLE
npm ERR! skillcrush-build-system@1.0.0 build: `webpack --mode=production --config=config/webpack.config.js`
npm ERR! Exit status 1
npm ERR! 
npm ERR! Failed at the skillcrush-build-system@1.0.0 build script 'webpack --mode=production --config=config/webpack.config.js'.
npm ERR! Make sure you have the latest version of node.js and npm installed.
npm ERR! If you do, this is most likely a problem with the skillcrush-build-system package,
npm ERR! not with npm itself.
npm ERR! Tell the author that this fails on your system:
npm ERR!     webpack --mode=production --config=config/webpack.config.js
npm ERR! You can get information on how to open an issue for this project with:
npm ERR!     npm bugs skillcrush-build-system
npm ERR! Or if that isn't available, you can get their info via:
npm ERR!     npm owner ls skillcrush-build-system
npm ERR! There is likely additional logging output above.

npm ERR! Please include the following file with any support request:
npm ERR!     /Users/wking/sites/learn_skillcrush/app/public/npm-debug.log
```

**Comment by wking-io** [comment]
I have confirmed that everything works fine in pre 1.0 tailwind and only happens in 1.0

**Comment by devcircus** [comment]
I think the beta versions of 1 target 8.9.0. The docs are for tailwind versions < 1.0.

**Comment by wking-io** [comment]
Do you know if the plan is to make it backwards compatible with the official release?

**Comment by adamwathan** [comment]
Yeah right now the beta only supports Node 8+, the fact that it says 6.9.0 in the package.json is a mistake. We could support 6.9.0 but it's end-of-life this month with no security updates, and it would make the syntax a lot uglier in the config stub that we scaffold with `tailwind init --full` so I don't really want to support it.

Do you have no choice but to use Node 6 going forward even though it's a security liability?

**Comment by wking-io** [comment]
Asking our deployment service now, but that is not on you. Node 6 will not be supported after this month so it is not your fault if our deployment service is not upgrading! :)
