### ISSUE TITLE
Upgrading beta4->beta5: TypeError: Cannot read property 'raws' of undefined

### ISSUE THREAD

**Issue by aphofstede** [tailwindcss/tailwindcss#873]
When upgrading form 1.0.0-beta.4 to beta.5, I get many of these errors during compilation:

```
ERROR in ./node_modules/extract-text-webpack-plugin/dist/loader.js?{"id":1,"omit":1,"remove":true}!./node_modules/vue-style-loader!./node_modules/css-loader!./node_modules/vue-loader/lib/style-compiler?{"vue":true,"id":"data-v-2cfae86b","scoped":false,"hasInlineConfig":true}!./node_modules/vue-loader/lib/selector.js?type=styles&index=0!./frontend/assets/js/components/FormDateRange.vue
Module build failed: ModuleBuildError: Module build failed: TypeError: Cannot read property 'raws' of undefined
    at formatNodes (/Users/alex/src/oris/node_modules/tailwindcss/lib/lib/formatCSS.js:21:14)
    at LazyResult.run (/Users/alex/src/oris/node_modules/vue-loader/node_modules/postcss/lib/lazy-result.js:277:20)
    at LazyResult.asyncTick (/Users/alex/src/oris/node_modules/vue-loader/node_modules/postcss/lib/lazy-result.js:192:32)
    at /Users/alex/src/oris/node_modules/vue-loader/node_modules/postcss/lib/lazy-result.js:197:27
    at process._tickCallback (internal/process/next_tick.js:68:7)
    at runLoaders (/Users/alex/src/oris/node_modules/webpack/lib/NormalModule.js:195:19)
    at /Users/alex/src/oris/node_modules/loader-runner/lib/LoaderRunner.js:367:11
    at /Users/alex/src/oris/node_modules/loader-runner/lib/LoaderRunner.js:233:18
    at context.callback (/Users/alex/src/oris/node_modules/loader-runner/lib/LoaderRunner.js:111:13)
    at loadPostcssConfig.then.catch.e (/Users/alex/src/oris/node_modules/vue-loader/lib/style-compiler/index.js:77:7)
    at process._tickCallback (internal/process/next_tick.js:68:7)
 @ ./node_modules/extract-text-webpack-plugin/dist/loader.js?{"id":1,"omit":1,"remove":true}!./node_modules/vue-style-loader!./node_modules/css-loader!./node_modules/vue-loader/lib/style-compiler?{"vue":true,"id":"data-v-2cfae86b","scoped":false,"hasInlineConfig":true}!./node_modules/vue-loader/lib/selector.js?type=styles&index=0!./frontend/assets/js/components/FormDateRange.vue
 @ ./frontend/assets/js/components/FormDateRange.vue
 @ ./node_modules/babel-loader/lib?{"cacheDirectory":true,"presets":[["env",{"modules":false,"targets":{"browsers":["> 2%"],"uglify":true}}],["babel-preset-env",{"targets":{"browsers":["last 2 versions"]}}]],"plugins":["transform-object-rest-spread",["transform-runtime",{"polyfill":false,"helpers":false}],"transform-runtime","transform-async-to-generator","transform-object-rest-spread","transform-class-properties","transform-es2015-arrow-functions",["component",{"libraryName":"element-ui","styleLibraryName":"theme-chalk"}]],"comments":false,"babelrc":false,"env":{"coverage":{"plugins":["istanbul"]}}}!./node_modules/vue-loader/lib/selector.js?type=script&index=0!./frontend/assets/js/components/FormActivePeriod.vue
 @ ./frontend/assets/js/components/FormActivePeriod.vue
 @ ./node_modules/babel-loader/lib?{"cacheDirectory":true,"presets":[["env",{"modules":false,"targets":{"browsers":["> 2%"],"uglify":true}}],["babel-preset-env",{"targets":{"browsers":["last 2 versions"]}}]],"plugins":["transform-object-rest-spread",["transform-runtime",{"polyfill":false,"helpers":false}],"transform-runtime","transform-async-to-generator","transform-object-rest-spread","transform-class-properties","transform-es2015-arrow-functions",["component",{"libraryName":"element-ui","styleLibraryName":"theme-chalk"}]],"comments":false,"babelrc":false,"env":{"coverage":{"plugins":["istanbul"]}}}!./node_modules/vue-loader/lib/selector.js?type=script&index=0!./frontend/assets/js/pages/contract/contract.vue
 @ ./frontend/assets/js/pages/contract/contract.vue
 @ ./frontend/assets/js/app.js
 @ multi ./frontend/assets/js/app.js ./frontend/assets/less/app.less
```
All of them seem to have an empty style tag. `<style></style>` Removing it seems to resolve the error.

**Comment by adamwathan** [comment]
Thanks! This is actually fixed on the `next` branch already so should be good in beta 6 which I'm going to try and release today.
